name: Check Notification

on: [push]

jobs:
  notifications:
    name: Rocket.Chat Notifications
    runs-on: ubuntu-latest
    steps:
      - uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@1.1.1

      - name: with mention on failure only
        uses: ./
        with:
          type: ${{ job.status }}
          job_name: ':robot_face: *Success no mention*'
          mention: 'here'
          mention_if: 'failure'
          commit: true
          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}
